
2022-08-06 08:57:34,872 INFO: errors [in /home/wndirangu/ALX/fyyur/app.py:593]
2022-08-06 09:01:48,020 INFO: errors [in /home/wndirangu/ALX/fyyur/app.py:593]
2022-08-06 09:08:50,816 INFO: errors [in /home/wndirangu/ALX/fyyur/app.py:594]
2022-08-06 09:09:03,657 ERROR: Exception on /venues [GET] [in /home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f8563c97110 (otid=0x7f8562b04740) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/wndirangu/ALX/fyyur/app.py", line 75, in venues
    venue_locations = db.session.query(
  File "<string>", line 2, in query
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4225, in __call__
    return self.class_(**local_kw)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 655, in _get_entrypoint
    cls = registry.load(name)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
2022-08-06 09:09:09,823 ERROR: Exception on /artists [GET] [in /home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f8563c97110 (otid=0x7f8562b07880) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/wndirangu/ALX/fyyur/app.py", line 272, in artists
    artists = db.session.query(Artist.id, Artist.name).all()
  File "<string>", line 2, in query
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4225, in __call__
    return self.class_(**local_kw)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 655, in _get_entrypoint
    cls = registry.load(name)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
2022-08-06 09:09:49,616 ERROR: Exception on /venues [GET] [in /home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f8562add6f0 (otid=0x7f8562a0c100) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/wndirangu/ALX/fyyur/app.py", line 75, in venues
    venue_locations = db.session.query(
  File "<string>", line 2, in query
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4225, in __call__
    return self.class_(**local_kw)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 655, in _get_entrypoint
    cls = registry.load(name)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
2022-08-06 09:09:53,214 ERROR: Exception on /venues [GET] [in /home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f8563c94040 (otid=0x7f8562a19080) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/wndirangu/ALX/fyyur/app.py", line 75, in venues
    venue_locations = db.session.query(
  File "<string>", line 2, in query
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4225, in __call__
    return self.class_(**local_kw)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 655, in _get_entrypoint
    cls = registry.load(name)
  File "/home/wndirangu/venvs/alx/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
